### PR TITLE
Video

### PR DESCRIPTION
**Pull request by Mimoja**

### CODE REVIEW

**Comment by ikalkov** [comment]
@Mimoja: see also EDIT above.

9) Remove "exit 0" in line 57 BEFORE patch?
10) Use a variable for the directory name "mounted"
11) Call "sync" after patching
11) Unmount the sdcard after patching
12) Remove the directory used for mounting

**Comment by Mimoja** [comment]
1) done
2) done
3) done
4)Because i have no idea, what might be needed to get it to work
5) done
6) done?
7) was dynamic, you did not like it.
8) TODO
9) done
10) done
11) Not necessary, if umount is performed. Added anyways. 
12) done
13) done

TODO: 
6,7,8

**Comment by Mimoja** [comment]
6,7,8 done, 13 as well

**Comment by ikalkov** [comment]
Merged manually

**Pull request closed without merging**
