### PR TITLE
Add dependency checking

### LINKED ISSUE #8: Check for installed binaries before starting scripts
inistall.sh
 - adb -> phablet-tools
- partprobe -> ?

gapps.sh
 - adb -> phablet-tools
 - lzip -> lzip

Examples here: http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script

### PR DESCRIPTION
**Pull request by Mimoja**
Fixes #8

### CODE REVIEW

**Comment by Mimoja** [comment]
But does it reallly make anything better to have to copy the function and the call to every distribution / version instead of sourcing one file and having the feature in the namespace for the rest of execution?
Therefore its just copying a file and adding two lines instead of inlining a new function, which in retrospective is harder to find when reviewing changes, especially when different devices request fundamentally different scripts?

**Comment by ikalkov** [comment]
1) I don't like the scripts to have any dependencies. If somebody decides to copy and use them somewhere else, they shouldn't have to modify it or copy multiple files.

2) Having 5 common lines of code in completely different scripts which have no common functionality, doesn't justify a common "core" file, which we would have to integrate in all of our build scripts for packaging.

3) Think about usability. Users have to immediately see the thing they need, instead of searching in a bunch of scripts they shouldn't touch.

**Comment by Mimoja** [comment]
done

**Comment by ikalkov** [comment]
@Mimoja Could you please remove your fork? I already asked you to work directly on RTAndroid repos.

**Pull request merged**
